### ISSUE TITLE
Possibile to add WHERE clause for customizable filtering

### ISSUE THREAD

**Issue by tayloramurphy** [MeltanoLabs/tap-postgres#185]
Would need to be per table

**Comment by visch** [comment]
I wonder if it just makes more sense to allow for arbitrary sql queries to be passed in. As I think the normal use case covers the "replication" use case and this type of filtering tends to be something folks want when they aren't trying to do "table replication" persay. 

Something like

```
extra_queries:
   - sql: select * from abc where c == 'Staff'
     primary_keys: ["id"]
     replication_key: updated_at
```    


What do you think @tayloramurphy

**Comment by tayloramurphy** [comment]
@visch that makes sense. Although it could be less "risky" from a pipeline breaking perspective to add it to any queries that are being generated.

**Comment by visch** [comment]
> @visch that makes sense. Although it could be less "risky" from a pipeline breaking perspective to add it to any queries that are being generated.

Depends on the use case I guess, what's the use case here?

**Comment by tayloramurphy** [comment]
@visch https://github.com/DouweM/tap-db2/commit/365afa7ecbe410eebf220871781bfd5758cded63 is a quick change that @DouweM made on a fork. 

@DouweM can you remind me of the specifics of this request?

**Comment by VertexToEdge** [comment]
https://github.com/VertexToEdge/tap-postgres/commit/17ba6b7c2c5643c44c1b9965f9397c418d0bb4da

@visch 
I worked about the feature that you said because i need.
If you want, you can try it like this.
```yaml
# meltano.yml
plugins:
  extractors:
  - name: tap-postgres
    namespace: tap_postgres
    pip_url: git+https://github.com/vertextoedge/tap-postgres.git@main#egg=meltanolabs-tap-postgres==0.1.4
```


@tayloramurphy
Hi, I'm building an EL pipeline for a client's PostgreSQL database and also newbie in this eco-system.
I want to perform incremental extracting, but I can't freely configure an appropriate incremental key.
Moreover, since the data is provided through a view table, partitioning is essential for query optimization.
But I'm wondering if adding a custom WHERE clause feature was the right approach.
Is there more suitable way with `tap-postgres` to control query generation?
