### ISSUE TITLE
Support filter_schema setting 

### ISSUE THREAD

**Issue by ShahBinoy** [MeltanoLabs/tap-postgres#215]
I am trying to perform ELT with meltano elt command against Postgres Tap (MeltanoLabs)
But I am getting error

`psycopg2.errors.InsufficientPrivilege: permission denied for schema pdr_ops`

Since the remote database is a third party Database, we do not have access to pdr_ops schema. Why is it trying to access `pdr_ops` schema. I only need to check against pdr schema

How can I limit my operations to only one schema pdr and not face this permissions error ?

meltano.yaml
=====
 
```
  - name: pdr
    inherit_from: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    capabilities: 
    - state
    select:
    - pdr-mv_participant_all.participant_id
    - pdr-mv_participant_all.id
    - pdr-mv_participant_all.modified
    metadata:
      pdr-mv_participant_all:
        replication-method: INCREMENTAL
        replication-key: modified
        view-key-properties: [id]
```
