### ISSUE TITLE
Exclude Matching Not Working as Expected

### ISSUE THREAD

**Issue by wesseljt** [MeltanoLabs/tap-postgres#253]
When using an exclude match in my cicd env everything is getting excluded even tables I did not specify. 

When running in the cicd env I would expect to see product_lines and product_lines2 but not customer_addr. Instead 0 tables are selected and everything is exlcuded. 

```
# Env = cicd

- name: tap-postgres--rds
  load_schema: test
  select:
  - "!public-customer_addr.*"        
  config:
    start_date: ${N_HOURS_AGO} 
    host: postgres.qa.host.com
    password: ${TAP_POSTGRES__RDS_PW}



#Extractor in .yml (meltano.yml) (not env specific)

  - name: tap-postgres--rds
    inherit_from: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      user: user
      database: test
    select:
    - public-customer_addr.*
    - public-product_lines.*
    - public-product_lines2.*
```

I have tested this with the sqlserver (buzzcutnorman version) tap and it works as expected.
